In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("sales_projeect_dataset.csv")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
994,536520,22092,BLUE PAISLEY TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
995,536520,22469,HEART OF WICKER SMALL,1,1/12/2010 12:43,1.65,14729.0,United Kingdom
996,536520,22100,SKULLS SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
997,536520,22096,PINK PAISLEY SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
998,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,1,1/12/2010 12:43,2.55,14729.0,United Kingdom

In [ ]:
df.shape

(999, 8)

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    1
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     1
Country        0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,1/12/2010 11:52,0.0,NaN,United Kingdom

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    1
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     1
Country        0
dtype: int64

In [ ]:
df=df.dropna()
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
994,536520,22092,BLUE PAISLEY TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
995,536520,22469,HEART OF WICKER SMALL,1,1/12/2010 12:43,1.65,14729.0,United Kingdom
996,536520,22100,SKULLS SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
997,536520,22096,PINK PAISLEY SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
998,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,1,1/12/2010 12:43,2.55,14729.0,United Kingdom

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [ ]:
# Checking duplicates
df.duplicated().sum()

np.int64(23)

In [ ]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,1/12/2010 11:45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,1/12/2010 11:49,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,1/12/2010 11:49,2.10,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,1/12/2010 11:49,1.65,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,1/12/2010 11:49,3.75,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,1/12/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,1/12/2010 11:49,1.65,17920.0,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,1/12/2010 11:49,2.10,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,1/12/2010 11:49,2.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,1/12/2010 12:15,1.65,15983.0,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 12:23,2.10,17968.0,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,1/12/2010 12:23,0.85,17968.0,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,1/12/2010 12:23,2.95,17968.0,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 12:23,2.10,17968.0,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,1/12/2010 12:31,2.55,17897.0,United Kingdom

In [ ]:
df[df.duplicated(subset=["InvoiceNo","StockCode"],keep=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
113,536381,71270,PHOTO CLIP LINE,1,1/12/2010 9:41,1.25,15311.0,United Kingdom
125,536381,71270,PHOTO CLIP LINE,3,1/12/2010 9:41,1.25,15311.0,United Kingdom
483,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,3,1/12/2010 11:45,6.35,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
...,...,...,...,...,...,...,...,...
912,536488,70007,HI TEC ALPINE HAND WARMER,1,1/12/2010 12:31,1.65,17897.0,United Kingdom
913,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,3,1/12/2010 12:31,2.55,17897.0,United Kingdom
916,536488,22144,CHRISTMAS CRAFT LITTLE FRIENDS,2,1/12/2010 12:31,2.10,17897.0,United Kingdom
989,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,3,1/12/2010 12:43,2.55,14729.0,United Kingdom
998,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,1,1/12/2010 12:43,2.55,14729.0,United Kingdom

In [ ]:
df[df.duplicated(keep=False)].sort_values(
    by=['InvoiceNo', 'StockCode'])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,1/12/2010 11:45,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,1/12/2010 11:45,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,1/12/2010 11:49,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,1/12/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,1/12/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,1/12/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,1/12/2010 11:49,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,1/12/2010 11:49,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,1/12/2010 11:49,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,1/12/2010 11:49,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,1/12/2010 11:49,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,1/12/2010 11:49,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,1/12/2010 11:49,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,1/12/2010 11:49,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,1/12/2010 11:49,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,1/12/2010 11:49,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,1/12/2010 11:49,2.10,17920.0,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,1/12/2010 11:49,2.10,17920.0,United Kingdom
615,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,1/12/2010 11:49,2.95,17920.0,United Kingdom
757,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,1/12/2010 12:15,1.65,15983.0,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,1/12/2010 12:15,1.65,15983.0,United Kingdom
808,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,1/12/2010 12:23,2.95,17968.0,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,1/12/2010 12:23,2.95,17968.0,United Kingdom
829,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 12:23,2.10,17968.0,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 12:23,2.10,17968.0,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 12:23,2.10,17968.0,United Kingdom
813,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,1/12/2010 12:23,0.85,17968.0,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,1/12/2010 12:23,0.85,17968.0,United Kingdom
890,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,1/12/2010 12:31,2.55,17897.0,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,1/12/2010 12:31,2.55,17897.0,United Kingdom

In [ ]:
df.duplicated().sum()

np.int64(23)

In [ ]:
df = df.drop_duplicates()
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
994,536520,22092,BLUE PAISLEY TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
995,536520,22469,HEART OF WICKER SMALL,1,1/12/2010 12:43,1.65,14729.0,United Kingdom
996,536520,22100,SKULLS SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
997,536520,22096,PINK PAISLEY SQUARE TISSUE BOX,1,1/12/2010 12:43,1.25,14729.0,United Kingdom
998,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,1,1/12/2010 12:43,2.55,14729.0,United Kingdom

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 975 entries, 0 to 998
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    975 non-null    object
 1   StockCode    975 non-null    object
 2   Description  975 non-null    object
 3   Quantity     975 non-null    int64
 4   InvoiceDate  975 non-null    object
 5   UnitPrice    975 non-null    float64
 6   CustomerID   975 non-null    float64
 7   Country      975 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.8+ KB

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

/tmp/ipykernel_1889/3633860036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 975 entries, 0 to 998
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    975 non-null    object
 1   StockCode    975 non-null    object
 2   Description  975 non-null    object
 3   Quantity     975 non-null    int64
 4   InvoiceDate  975 non-null    datetime64[ns]
 5   UnitPrice    975 non-null    float64
 6   CustomerID   975 non-null    float64
 7   Country      975 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 100.8+ KB

In [ ]:
df['CustomerID'] = df['CustomerID'].astype('int64')

/tmp/ipykernel_1889/2371841825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CustomerID'] = df['CustomerID'].astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 975 entries, 0 to 998
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    975 non-null    object
 1   StockCode    975 non-null    object
 2   Description  975 non-null    object
 3   Quantity     975 non-null    int64
 4   InvoiceDate  975 non-null    datetime64[ns]
 5   UnitPrice    975 non-null    float64
 6   CustomerID   975 non-null    int64
 7   Country      975 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 100.8+ KB

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
# Checking negative values and zero'th value of 'Quantity'
check_negative=df["Quantity"]< 0
check_negative.sum()

np.int64(10)

In [ ]:
check_zero=df["Quantity"]==0
check_zero.sum()

np.int64(0)

In [ ]:
# Checking negative values and zero'th value of 'Unit Price'
check_negative=df["UnitPrice"]< 0
check_negative.sum()

np.int64(0)

In [ ]:
check_zero=df["UnitPrice"]==0
check_zero.sum()

np.int64(0)

In [ ]:
df[df["Quantity"]< 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-01-12 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-01-12 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-01-12 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-01-12 10:24:00,3.45,17548,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-01-12 10:24:00,1.65,17548,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-01-12 10:24:00,1.65,17548,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-01-12 12:38:00,4.25,17897,United Kingdom

In [ ]:
negative_rows=df[df["Quantity"]< 0].copy()
negative_rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
141,C536379,D,Discount,-1,2010-01-12 09:41:00,27.50,14527,United Kingdom,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-01-12 09:49:00,4.65,15311,United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-01-12 10:24:00,1.65,17548,United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom,-6.96
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-01-12 10:24:00,0.29,17548,United Kingdom,-6.96
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-01-12 10:24:00,3.45,17548,United Kingdom,-41.40
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-01-12 10:24:00,1.65,17548,United Kingdom,-19.80
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-01-12 10:24:00,1.65,17548,United Kingdom,-39.60
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-01-12 12:38:00,4.25,17897,United Kingdom,-25.50

np.float64(24605.98)

In [ ]:
# Creating sales column
df["Sales"]=df["Quantity"]*df["UnitPrice"]
df["Sales"]

/tmp/ipykernel_1889/265600366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sales"]=df["Quantity"]*df["UnitPrice"]

0      15.30
1      20.34
2      22.00
3      20.34
4      20.34
       ...
994     1.25
995     1.65
996     1.25
997     1.25
998     2.55
Name: Sales, Length: 975, dtype: float64

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
994,536520,22092,BLUE PAISLEY TISSUE BOX,1,2010-01-12 12:43:00,1.25,14729,United Kingdom,1.25
995,536520,22469,HEART OF WICKER SMALL,1,2010-01-12 12:43:00,1.65,14729,United Kingdom,1.65
996,536520,22100,SKULLS SQUARE TISSUE BOX,1,2010-01-12 12:43:00,1.25,14729,United Kingdom,1.25
997,536520,22096,PINK PAISLEY SQUARE TISSUE BOX,1,2010-01-12 12:43:00,1.25,14729,United Kingdom,1.25
998,536520,22583,PACK OF 6 HANDBAG GIFT BOXES,1,2010-01-12 12:43:00,2.55,14729,United Kingdom,2.55

In [ ]:
# CALCULATING TOTAL SALES/  Net sales: sales of all negtive & positive rows
total_sales = df['Sales'].sum()
total_sales

np.float64(24406.85)

In [ ]:
# calculating gross sales: Caluculating sales of only positive rows
gross_sales = df.loc[df["Quantity"] > 0, "Sales"].sum()
gross_sales

np.float64(24605.98)

In [ ]:
# showing difference between net sales and gross sales
impact_sales = gross_sales - total_sales
impact_sales

np.float64(199.13000000000102)

In [ ]:
df.to_csv("project_fie.csv",index = False)